"""
============================================
add auth_admin and admin_token tables
============================================

Revision ID: 20260713_0001
Revises: 99b440bc3a16
Create Date: 2026-07-13 10:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "20260713_0001"
down_revision: Union[str, None] = "99b440bc3a16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_admins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="管理员ID"),
        sa.Column("username", sa.String(length=50), nullable=False, comment="用户名"),
        sa.Column("password_hash", sa.String(length=255), nullable=False, comment="密码哈希"),
        sa.Column("nickname", sa.String(length=50), nullable=False, server_default="", comment="昵称"),
        sa.Column("is_super", sa.Boolean(), nullable=False, server_default=sa.text("0"), comment="是否超管"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1"), comment="是否启用"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"), comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="uk_username"),
        comment="后台管理员表",
    )
    op.create_index(op.f("ix_auth_admins_username"), "auth_admins", ["username"], unique=True)

    op.create_table(
        "admin_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="id"),
        sa.Column("admin_id", sa.Integer(), nullable=False, comment="管理员ID"),
        sa.Column("token", sa.String(length=64), nullable=False, comment="登录Token"),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="过期时间"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1"), comment="是否有效"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"), comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"), comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uk_token"),
        comment="管理员Token表",
    )
    op.create_index(op.f("ix_admin_tokens_admin_id"), "admin_tokens", ["admin_id"])
    op.create_index(op.f("ix_admin_tokens_token"), "admin_tokens", ["token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_tokens")
    op.drop_table("auth_admins")
    # ### end Alembic commands ###
